
# --------- High Level Settings ---------

# Project information
site_name: 314 Docs
site_description: Documentation for INFO 314
site_author: Ben Walchenbach
# site_url: https://squidfunk.github.io/mkdocs-material/

# Repository
# repo_name: squidfunk/mkdocs-material
# repo_url: https://github.com/squidfunk/mkdocs-material
edit_uri: ""



# --------- Main Settings ---------

# Page tree
nav:
  - Welcome:
      - Welcome: index.md
      - Assignment Template: assignments.md
      - Asking for help: contact.md
      - Intro to Markdown: markdown.md
      - Intro to Bash: bash.md
  - Course Preparation:
      - Pi Materials: course-prep/pi-materials.md
      - Install Wireshark: course-prep/wireshark-install.md
      - Digital Ocean Signup: course-prep/do.md
      - Core Skills Lab: course-prep/core-skills-lab.md
      - Install Python: course-prep/install-python.md
  - Assignments/Labs:
      - Project 1:
          - Overview: assignments/project-1/overview.md
          - Setup: assignments/project-1/setup.md
      - Project 2:
          - Overview: assignments/project-2/overview.md
          - Setup: assignments/project-2/setup.md
      - Project 3:
          - Overview: assignments/project-3/overview.md
          - Setup: assignments/project-3/setup.md
      - Project 4 - DNS Resolvers: # assignments/project-4.md
          - Overview: assignments/project-4/overview.md
          - Setup: assignments/project-4/setup.md
          - Windows DNS Tools: assignments/project-4/windows-dns-tools.md
  - Troubleshooting:
      - General: trouble/basics.md
      - DHCP / dhcpd: trouble/dhcp.md
      - Interfaces / systemd: trouble/interfaces.md
      - NAT / iptables: trouble/nat.md
      - DNS / bind9: trouble/dns.md
      - Final Project: trouble/final.md
  - After this Course:
      - Use Your Raspberry Pi: beyond/use-your-pi.md
      

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    # primary: indigo
    primary: deep purple
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"



# --------- Optional Settings---------

# Customization
# extra:
#   social:

#     - type: github-alt
#       link: https://github.com/i314-campbell-wi19/project-tutorials
#     - type: linkedin
#       link: http://struct.cc
#     - type: poll-in
#       link: https://twitter.com/squidfunk
#     - type: linkedin
#       link: https://linkedin.com/in/squidfunk

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Copyright
copyright: 'Copyright &copy; 2016 - 2019 Martin Donath'